# Generated by Django 5.0.7 on 2024-10-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_farmer_registration_specialist_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer_registration',
            old_name='admin_approvel',
            new_name='admin_approval',
        ),
        migrations.RenameField(
            model_name='specialist_registration',
            old_name='admin_approvel',
            new_name='admin_approval',
        ),
        migrations.RenameField(
            model_name='supplier_registration',
            old_name='admin_approvel',
            new_name='admin_approval',
        ),
    ]
