# Generated by Django 5.0.7 on 2024-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_admin_approvel_farmer_registration_admin_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_registration',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='specialist_registration',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='supplier_registration',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
