# Generated by Django 5.0.7 on 2024-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_farmer_registration_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('video_link', models.CharField(max_length=50, null=True)),
                ('posted_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
