# Generated by Django 5.0.7 on 2024-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_categories',
            name='category_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
