# Generated by Django 5.0.7 on 2024-10-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier_registration'),
        ),
    ]
