# Generated by Django 5.0.7 on 2024-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_add_product_supplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
