# Generated by Django 5.0.7 on 2024-10-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_add_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_product',
            new_name='Add_products',
        ),
    ]
