# Generated by Django 5.0.7 on 2024-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shipping_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
