# Generated by Django 5.0.7 on 2024-10-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_booking_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='farmer_id',
        ),
    ]
