# Generated by Django 5.0.7 on 2024-10-09 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_user_id_booking_farmer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_specialist_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, null=True)),
                ('message_on', models.DateTimeField(null=True)),
                ('reply', models.CharField(max_length=100, null=True)),
                ('reply_on', models.DateTimeField(null=True)),
                ('farmer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer_registration')),
                ('specialist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.specialist_registration')),
            ],
        ),
    ]
