# Generated by Django 5.0.7 on 2024-10-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_farmer_specialist_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('feedback_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
