# Generated by Django 5.0.7 on 2024-10-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='farmer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.farmer_registration'),
        ),
    ]
