# Generated by Django 5.0.7 on 2024-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_feedback_farmer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_status',
            field=models.BooleanField(default=False),
        ),
    ]
