# Generated by Django 5.0.7 on 2024-10-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_booking_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
