# Generated by Django 5.0.7 on 2024-10-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_feedback_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='specialist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.specialist_registration'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier_registration'),
        ),
    ]
